spring.application.name=library-service
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/bookshelf_idp
spring.datasource.username=postgres
spring.datasource.password=BLoom--2820

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.open-in-view=false

jwt.secret=bookshelf-idp-secret-key-minimum-32-chars
jwt.expiration=86400000

notification.service.url=http://localhost:8084

springdoc.api-docs.path=/v3/api-docs